name: envlight-mlp
xyz2lonlat_mode: null # or blender
envlight_config:
  hdr_filepath: null
  scale: 0.5
  bias: 0.25
  base_res: 512
  num_SGs: 128
  encoding_config:
    otype: Grid
    type: Hash
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 15
    base_resolution: 16
    per_level_scale: 1.447269237440378
    interpolation: Linear
  mlp_network_config:
    otype: FullyFusedMLP
    activation: ReLU
    output_activation: Softplus
    n_neurons: 64
    n_hidden_layers: 1
