# @package _global_.explicit_branch

dataset_name: subject_01

distill_dataset:
  name: distill
#  root_dir: "./data_GS/peoplesnapshot_arah-format/people_snapshot_public"
  root_dir: "./load/rana/train_p1"
  motion_root: "./load/distill_pose"
  motion: rana_pose_aa_all # "cape_00096_longshort_punching" # cape_00032_shortlong_soccer # aist
  downscale: 1 # 2
  subject: subject_01
  split: train
  gender: male

  train_frames: [ 0, 310, 1 ]
  val_frames: [ 0, 310, 1 ]
  test_frames:
    pose: [0, 310, 1] # [ 0, 128, 1 ] for punching # [ 0, 101, 1 ] for soccer
#    pose: [ 0, 456, 4 ]
    all: [ 0, 310, 1 ]
  predict_frames: [0, 0, 1]

#  img_hw:
#    - 540
#    - 540

  resolution: -1
  white_background: true # false
  data_device: cuda
  eval: false
  distill_pose_data_dir: "exp/intrinsic-avatar-subject_01/rana_s01/save/it0-test"
  alpha_data_dir: "exp/intrinsic-avatar-subject_01/rana_s01/save/it0-test-with-alpha"
  rest_pose: a_pose