# @package _global_.explicit_branch

dataset_name: ps_male_3

distill_dataset:
  name: distill
#  root_dir: "./data_GS/peoplesnapshot_arah-format/people_snapshot_public"
  root_dir: "./load/peoplesnapshot"
  motion_root: "./load/distill_pose"
  motion: da_pose_aa # "cape_00096_longshort_punching" # cape_00032_shortlong_soccer # aist
  downscale: 2 # 2
  subject: male-3-casual
  split: train

  train_frames: [ 0, 10, 1 ]
  val_frames: [ 0, 10, 1 ]
  test_frames:
    pose: [0, 10, 1] # [ 0, 128, 1 ] for punching # [ 0, 101, 1 ] for soccer
#    pose: [ 0, 456, 4 ]
    all: [ 0, 10, 1 ]
  predict_frames: [0, 0, 1]

#  img_hw:
#    - 540
#    - 540

  resolution: -1
  white_background: true # false
  data_device: cuda
  eval: false
  distill_pose_data_dir: "exp/intrinsic-avatar-male-3-casual/male-3-casual-tpose/save/it0-test"
  alpha_data_dir: "exp/intrinsic-avatar-male-3-casual/male-3-casual-tpose/save/it0-test-with-alpha"
  rest_pose: a_pose