train_split: 'train'
val_split: 'val'
test_split: 'test'
name: synthetichumanpp
dataroot: ./load/synthetichumanpp/${dataset.subject}
subject: jody
gender: neutral
scene_aabb: [-1.0048515, -1.3139347, -0.9065285,  1.0558258,  0.7467426, 1.1541488]
opt:
  train:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 99
    skip: 1
    downscale: 2
    sampler: ${sampler}
    fitting: false
    refine: false
  val:
    num_workers: 0
    batch_size: 1
    start: 99
    end: 99
    skip: 1
    downscale: 2
  test:
    num_workers: 0
    batch_size: 1
    start: 0
    end: 99
    skip: 1
    downscale: 2
