train_split: 'train'
val_split: 'val'
test_split: 'test'
name: peoplesnapshot
dataroot: ./load/peoplesnapshot/${implicit_branch.dataset.subject}/
subject: male-2-casual
gender: male
scene_aabb: [-1.25, -1.55, -1.25, 1.25, 0.95, 1.25]
hdri_filepath: null
opt:
  train:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 311
    skip: 3
    downscale: 2
    sampler: ${implicit_branch.sampler}
    fitting: false
    refine: false
  val:
    num_workers: 0
    batch_size: 1
    start: 312
    end: 312
    skip: 3
    downscale: 2
  test:
    num_workers: 0
    batch_size: 1
#    start: 312
#    end: 470
    start: 0
    end: 311
    skip: 3
    downscale: 2
