defaults:
  - implicit_branch/config
  - explicit_branch/config
  - _self_
  # - implicit_branch/dataset: peoplesnapshot/male-3-casual
  # - explicit_branch/distill_dataset: ps_IA_distill_male_3
  # - explicit_branch/dataset: ps_IA_male_3
#  - override implicit_branch/pose_correction: pose_residual_enable
#  - override implicit_branch/light: envlight_tensor # envlight_tensor_blender # envlight_tensor # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  - override explicit_branch/texture: shallow_mlp_rigid_noframe_ref_normal
  - override explicit_branch/rigid: smpl_knn # smpl_nn smpl_knn skinning_field
  - override explicit_branch/non_rigid: identity #ps_male we use identity # identity for RANA
  - override explicit_branch/pose_correction: none
  - override explicit_branch/option: iter50k
  - override explicit_branch/distill_dataset: ps_IA_distill_male_3
  - override explicit_branch/dataset: ps_IA_male_3 # ps_IA_male_3 # ps_IA_animation_male_3 ps_IA_animation_male_3_punching
  - override implicit_branch/dataset: peoplesnapshot/male-3-casual # animation/male-3-casual-tpose # animation/male-3-casual peoplesnapshot/male-3-casual
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Disable Hydra's automatic logging
hydra:
  output_subdir: null
  run:
    dir: .
  job:
    chdir: false

implicit_branch:
  system:
    name: intrinsic-avatar-system-GS
    loss:
      lambda_distill_points: 0.001
  deformer:
    rigid_deformer:
      deformer_config:
        cano_pose: "A_pose" # "ps_female_3_pose" "ps_pose" "A_pose" # "star_pose" for ps_male_3 # ps_pose for female3

  tag: 'male-3-casual' 
#  mode: test



  # resume: ./exp/intrinsic-avatar-male-3-casual/male-3-casual/ckpt/epoch=219-step=25000.ckpt


  trainer:
    max_steps: 25000

explicit_branch:
  base_res: 512 
  pipeline:
    convert_SHs_python: true
    compute_cov3D_python: false # True for 3dgs, False for 2dgs
  test_interval: 2000
  save_iterations: [10000, 20000, 25000, 30000, 40000, 50000]
  checkpoint_iterations: [10000, 20000, 25000, 30000, 40000, 50000]
  rendering_type: 'forward_pbr' # 'forward_pbr' 'diff_pbr' 'deferred_pbr' 
  model:
    pbr_iteration: 20000 # 20000
    gaussian:
      delay: 100 





  # for ps_male_3
  distill_cano: true
  build_occ: true
  enable_occ_type: gaussian
  enable_occ_1spp: true
  # distill density setting
  distill_density_iter: [510, 2000, 4000, 10000, 17000, 25000, 29000]
  density_distillation_K: 10
  density_distillation_min: 0.0003
  density_distillation_max: 0.01
  # mode: test # predict
  # load_ckpt: /scratch/shared/beegfs/zeren/instant-nsr-pbr/instant-nsr-pbr/exp/ps_male3_2dgs_smpl_nonrigid_IA_canodistill_knn_scalereg_rigid_density10000102_distillpose_apose_correct/ckpt30000.pth
  # hdri: /scratch/shared/beegfs/zeren/instant-nsr-pbr/instant-nsr-pbr/Environment_Maps/high_res_envmaps_2k/cambridge_2k.hdr


  opt:
    lambda_scale: [0, 5000, 0.1]
    # point-based distillation loss
    lambda_normal_similarity: 0.1 # 0.1
    lambda_pos_distill: 0.05 # 0.05
    lambda_materials: 0.08 # 0.08
    # image-based distillation loss
    lambda_env: 2.000 # 0.010 for RANA # 0.005
    lambda_distill_image: 1.0 # 0.1 for PS # 0.2 for RANA
    lambda_distill_image_rm: 0.01 # 0.1 for ps # 0.0 for RANA

    densify_until_iter: 16000 # 20000
    densify_grad_threshold: 0.0002 # 0.0002

    # for 2dgs
    lambda_dist: 100
    lambda_normal: 0.05

    # scale regularization
    lambda_scale_reg: 5 # 0 (0 for rana)

    # lpips
    lambda_perceptual: 5e-2 # 1e-1 # 2e-1 # 5e-2 # 1e-2

    # a_pose
    lambda_skinning: [15,1000,0.3]

training_mode: distill # joint, distill, teacher, student
gs_type: 2dgs # 2dgs, 3dgs
