train_split: 'train'
val_split: 'val'
test_split: 'test'
name: animation
dataroot_train: ./load/peoplesnapshot/${implicit_branch.dataset.subject}/
dataroot_test: ./load/animation/${implicit_branch.dataset.motion}
subject: female-3-casual
motion: aist # cape_00032_shortlong_soccer
gender: female
scene_aabb: [-1.25, -1.55, -1.25, 1.25, 0.95, 1.25]
hdri_filepath: ./Environment_Maps/high_res_envmaps_2k/cambridge_2k.hdr # cambridge_2k city
opt:
  train:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 445
    skip: 4
    downscale: 1
    fitting: false
    refine: false
  test:
    num_workers: 0
    batch_size: 1
    start: 0
    # end: 101
    end: 319
    skip: 1
    downscale: 2
    hdri_filepath: ./Environment_Maps/high_res_envmaps_2k/cambridge_2k.hdr # cambridge_2k city
